stages:
  - test
  - deploy

default:
  image: node:14.17.0-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-online

.setup_ssh:
  before_script:
    - 'which ssh-agent || (apk add --update openssh curl bash git)'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts


lint:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run check:format

deploy:
  stage: deploy
  extends:
    - .setup_ssh
  variables:
    REPOSITORY_URL: 'git@gitlab.com:benaxscope/javascript.ninja-ci-cd-backend.git'
    DEPLOY_DST: '/home/deploy/app/$CI_COMMIT_REF_SLUG'
    DB_NAME: $CI_COMMIT_REF_SLUG
  script:
    - npm i -g pm2
    - ssh -q $SSH_USER@$SSH_HOST [[ ! -d "$DEPLOY_DST" ]] && pm2 deploy ecosystem.config.js production setup
    - |
      ssh $SSH_USER@$SSH_HOST <<EOF
        echo "DB_NAME=$DB_NAME" > $DEPLOY_DST/.env
        echo "DB_USER=$DB_USER" >> $DEPLOY_DST/.env
        echo "DB_PASSWORD=$DB_PASSWORD" >> $DEPLOY_DST/.env
        echo "SECRET=$SECRET" >> $DEPLOY_DST/.env
      EOF
    - pm2 deploy ecosystem.config.js production --update-env
  environment:
    name: production
    url: http://$CI_COMMIT_REF_SLUG.$APP_HOST/
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'