stages:
  - lint

cache:
  key:
    files:
      - package-lock.json
  path:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-online


eslint:
  image: node:14.17.0-alpine
  stage: lint
  script:
    - npm install
    - npm run lint
