---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-__CI_ENVIRONMENT_SLUG__
  namespace: ci-cd-workshop
  labels:
    app: postgres
    ref: __CI_ENVIRONMENT_SLUG__
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
