name: Create review app

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          rsync -a -r --progress --human-readable --delete \
          --exclude-from .gitignore \
          --include-from .deploylist \
          --exclude public \
          --exclude ecosystem.config.js \
          . $SSH_USER@$SSH_HOST:~/app/${{ github.head_ref }}/
      - name: Restarting the app
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh $SSH_USER@$SSH_HOST "cp ~/ecosystem.config.js ~/app/${{ github.head_ref }}/ && pushd ~/app/${{ github.head_ref }} && sed -i 's/realworld-db/${{ github.head_ref }}/' ecosystem.config.js && pm2 stop ecosystem.config.js && ./bin/create-db-copy.sh ${{ secrets.DB_PASSWORD }} ${{ github.head_ref }} && npm ci --legacy-peer-deps && pm2 restart ecosystem.config.js --name ${{ github.head_ref }} --env production --update-env && popd"
  review:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - id: check-branch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/owner/${repo}/git/ref/:ref
          owner: "benax-se"
          repo: Javascript.ninja-CI-CD-frontend
          ref: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        continue-on-error: true
      - if: steps.check_branch.output.status == 200
        name: Trigger frontend review app
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/publish-review-app.yml/dispatches
          owner: benax-se
          repo: Javascript.ninja-CI-CD-frontend
          ref: ${{ github.head_ref }}
          inputs: |
            refName: ${{ github.head_ref }}
            dst: ${{ github.head_ref }}
      - if: steps.check_branch.output.status != 200
        name: Trigger frontend review app
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/publish-review-app.yml/dispatches
          owner: benax-se
          repo: Javascript.ninja-CI-CD-frontend
          ref: main
          inputs: |
            refName: main
            dst: ${{ github.head_ref }}
          
