
name: Deploy
on:
  push:
    branches: [main]
  # специальное событие, которое происходит при ручном вызове workflow
  workflow_dispatch:

jobs:
jobs:
  # название job, на которое можно ссылаться из других мест,
  # например, когда нам нужно указать, что две jobs
  # работают последовательно:
  # jobs:
  #   build:
  #   eslint:
  #     needs: build
  eslint:
    # имя для отображения в интерфейсе GitHub
    name: ESLint
    # обязательный параметр, который указывает где будет запущена job: облачнный runner, self-hosted и т.д.
    runs-on: ubuntu-latest
    # последовательные задачи (шаги), важно помнить, что переменные окружения не сохраняются
    # между шагами и их нужно пробрасывать, если требуется.
    steps:
      # указываем action, который будет запущен как часть job
      # В текущем случае это клонирование репозитория
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.0
          cache: 'npm'
      # Установка зависимостей проекта
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      # Запуск ESLint
      - name: Lint source code with ESLint
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          # создаем директорию для ключа
          mkdir -p ~/.ssh
          # выводим содержимое нашей переменной окружения в файл
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ci-key
          # ставим нужные безопасные права
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/ci-key
          # Добавляем отпечаток сервера
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - name: Copy files to the server
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # заливаем файлы при помощи rsync
        run: |
          rsync -a --progress --human-readable --delete \
          # исключить все, что есть в .gitignore
          --exclude-from '.gitignore' \
          # не загружаем .gitignore
          --exclude .gitignore \
          # не загружаем .git
          --exclude .git \
          # Не удаляем директорию с нашим фронтендом
          --exclude public \
          . deploy@$REMOTE_HOST:~/realworld/
      # job для перезапуска приложения при помощи pm2
      - name: Restart the application
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          ssh deploy@$REMOTE_HOST "pushd ~/realworld && npm install && popd && pm2 restart ecosystem.config.js"