# имя нашего workflow. Используется исключительно для отображения в интерфейсе GitHub
name: test

# правила срабатывания - события GitHub, на которые
# должен срабатывать текущий workflow.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# workflow состоит из одной или нескольких job
# job работают параллельно по умолчанию
jobs:
  # название job, на которое можно ссылаться из других мест,
  # например, когда нам нужно указать, что две jobs
  # работают последовательно:
  # jobs:
  #   build:
  #   eslint:
  #     needs: build
  eslint:
    # имя для отображения в интерфейсе GitHub
    name: ESLint
    # обязательный параметр, который указывает где будет запущена job: облачнный runner, self-hosted и т.д.
    runs-on: ubuntu-latest
    container: node:14.17.0-alpine
    # последовательные задачи (шаги), важно помнить, что переменные окружения не сохраняются
    # между шагами и их нужно пробрасывать, если требуется.
    steps:
      # Установка зависимостей проекта
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      # Запуск ESLint
      - name: Lint source code with ESLint
        run: npm run lint