name: Reset databse

on:
  workflow_dispatch:

jobs:
  reset-db:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: "Resetting the database"
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh $SSH_USER@$SSH_HOST "pushd ~/app/${{ github.head_ref }} && pm2 stop ecosystem.config.js && ./bin/create-db-copy.sh ${{ secrets.DB_PASSWORD }} $GITHUB_REF && pm2 restart ecosystem.config.js --name ${{ github.head_ref }} --env production --update-env && popd"
